Import('env')

blif = env.Synthesize('top', ['build/Top.v', '#../deps/chisel-jtag/external/vsrc/AsyncResetReg.v'])
asc = env.PlaceRoute(blif, pcf='ice40hx8k-b-evn.pcf')
bits = env.BitGen(asc)
report = env.Timing(asc)

env.Default(bits, report)

env.Alias('prog', [env.BitProg(bits), report])